### ISSUE TITLE
converting more than one pst

### ISSUE THREAD

**Issue by GuitarBilly** [juanirm/pst-converter#3]
hello,
when I put more than one pst file in the in/ folder only the first gets processed.
Looking at the manpage of readpst https://www.five-ten-sg.com/libpst/rn01re01.html it seems it accepts one file as input.

So I simply updated convert.sh to loop all pst files in the in/ folder like this:
```
#!/bin/bash
for INDIRfile in $INDIR/*.pst
do
  readpst -u -o $OUTDIR $INDIRfile 
done
...
```

**Comment by juanirm** [comment]
Good catch.
Would you be interested in doing a PR? If not, I'll update it later on.
Thanks!

**Comment by GuitarBilly** [comment]
looks good to me.

**Comment by GuitarBilly** [comment]
.
